const recordActionTypes = {
    FETCH_NOTES_START: "FETCH_NOTES_START",
    FETCH_NOTES_SUCCESS: "FETCH_NOTES_SUCCESS",
    FETCH_NOTES_FAILURE: "FETCH_NOTES_FAILURE",
    ADD_NOTE_START: "ADD_NOTE_START",
    ADD_NOTE_SUCCESS: "ADD_NOTE_SUCCESS",
    ADD_NOTE_FAILURE: "ADD_NOTE_FAILURE",
};

export default recordActionTypes;