const leadActionTypes = {
    FETCH_LEADS_START: "FETCH_LEADS_START",
    FETCH_LEADS_SUCCESS: "FETCH_LEADS_SUCCESS",
    FETCH_LEADS_FAILURE: "FETCH_LEADS_SUCCESS",
    CHANGE_STAGE_START: "CHANGE_STAGE_START",
    CHANGE_STAGE_SUCCESS: "CHANGE_STAGE_SUCCESS",
    CHANGE_STAGE_FAILURE: "CHANGE_STAGE_FAILURE"
};

export default leadActionTypes;